import type { ExtractedPreview, LinkType } from "./types";

/** Minimum transcript length to run summarization and candidate generation. */
export const MIN_YOUTUBE_TRANSCRIPT_LENGTH = 300;

export const TRANSCRIPT_PREVIEW_CHARS = 500;

export type TranscriptDiagnostic = {
  /** True when link type is YouTube (transcript rules apply). */
  applicable: boolean;
  success: boolean;
  length: number;
  preview500: string;
  language: string | null;
  isAutoGenerated: boolean;
  failureReason: string | null;
};

export function buildTranscriptDiagnostic(
  linkType: LinkType,
  extracted: ExtractedPreview
): TranscriptDiagnostic {
  if (linkType !== "youtube") {
    return {
      applicable: false,
      success: false,
      length: 0,
      preview500: "",
      language: null,
      isAutoGenerated: false,
      failureReason: null,
    };
  }

  const text = extracted.youtubeTranscript?.trim() ?? "";
  const success = text.length > 0;
  const failureReason = success
    ? null
    : extracted.extractNote?.trim() ||
      "영상 자막을 찾지 못했습니다. 자막이 켜져 있는 영상인지 확인해 주세요.";

  return {
    applicable: true,
    success,
    length: text.length,
    preview500: text.slice(0, TRANSCRIPT_PREVIEW_CHARS),
    language: extracted.youtubeTranscriptLanguage ?? null,
    isAutoGenerated: extracted.youtubeTranscriptAuto ?? false,
    failureReason,
  };
}

export function validateYouTubeTranscriptForCandidates(
  diagnostic: TranscriptDiagnostic,
  supplementalTextLength = 0
): { ok: true } | { ok: false; error: string } {
  if (!diagnostic.applicable) {
    return { ok: true };
  }

  const supplemental = Math.max(0, supplementalTextLength);
  const transcriptLen = diagnostic.length;

  if (supplemental >= MIN_YOUTUBE_TRANSCRIPT_LENGTH) {
    return { ok: true };
  }

  if (!diagnostic.success || transcriptLen === 0) {
    if (supplemental > 0) {
      return {
        ok: false,
        error: `영상 자막을 찾지 못았고, 보강 텍스트도 짧습니다 (${supplemental.toLocaleString("ko-KR")}자). 보강 텍스트만으로 진행하려면 최소 ${MIN_YOUTUBE_TRANSCRIPT_LENGTH.toLocaleString("ko-KR")}자 이상 붙여 넣어 주세요.`,
      };
    }
    return {
      ok: false,
      error:
        diagnostic.failureReason ||
        "영상 자막을 찾지 못했습니다. 원문 보강 텍스트를 붙이거나, 자막이 있는 영상 링크를 사용해 주세요.",
    };
  }

  if (transcriptLen + supplemental < MIN_YOUTUBE_TRANSCRIPT_LENGTH) {
    return {
      ok: false,
      error: `영상 자막과 보강 텍스트를 합쳐도 짧습니다 (자막 ${transcriptLen.toLocaleString("ko-KR")}자 + 보강 ${supplemental.toLocaleString("ko-KR")}자). 합쳐 최소 ${MIN_YOUTUBE_TRANSCRIPT_LENGTH.toLocaleString("ko-KR")}자 이상이 필요합니다.`,
    };
  }

  return { ok: true };
}
