const FETCH_TIMEOUT_MS = 22_000;
const MAX_TRANSCRIPT_CHARS = 120_000;

export type YouTubeTranscriptResult =
  | {
      ok: true;
      text: string;
      languageCode: string;
      isAutoGenerated: boolean;
    }
  | { ok: false; reason: string };

type CaptionTrack = {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string };
};

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/&#x27;/gi, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) =>
      String.fromCharCode(parseInt(h, 16))
    );
}

export function parseYouTubeVideoId(pageUrl: string): string | null {
  try {
    const u = new URL(pageUrl);
    const host = u.hostname.replace(/^www\./i, "").toLowerCase();

    if (host === "youtu.be") {
      const id = u.pathname.replace(/^\//, "").split("/")[0];
      return id || null;
    }

    if (host === "youtube.com" || host.endsWith(".youtube.com")) {
      const v = u.searchParams.get("v");
      if (v) return v;
      const m = u.pathname.match(/\/(?:embed|v|shorts|live)\/([^/?]+)/i);
      if (m?.[1]) return m[1];
    }
  } catch {
    return null;
  }
  return null;
}

function extractJsonObjectAfterMarker(
  html: string,
  marker: string
): Record<string, unknown> | null {
  const idx = html.indexOf(marker);
  if (idx === -1) return null;
  const start = html.indexOf("{", idx + marker.length);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escape = false;

  for (let i = start; i < html.length; i += 1) {
    const c = html[i];
    if (inString) {
      if (escape) escape = false;
      else if (c === "\\") escape = true;
      else if (c === '"') inString = false;
      continue;
    }
    if (c === '"') {
      inString = true;
      continue;
    }
    if (c === "{") depth += 1;
    else if (c === "}") {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(start, i + 1)) as Record<string, unknown>;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

function getCaptionTracks(
  player: Record<string, unknown>
): CaptionTrack[] {
  const captions = player.captions as Record<string, unknown> | undefined;
  const list = captions?.playerCaptionsTracklistRenderer as
    | Record<string, unknown>
    | undefined;
  const tracks = list?.captionTracks;
  if (!Array.isArray(tracks)) return [];
  return tracks.filter(
    (t): t is CaptionTrack => !!t && typeof t === "object" && "baseUrl" in t
  );
}

function trackScore(track: CaptionTrack): number {
  const lang = (track.languageCode || "").toLowerCase();
  const isAsr = track.kind === "asr";
  let score = 0;
  if (lang === "ko" || lang.startsWith("ko")) score += 100;
  else if (lang === "en" || lang.startsWith("en")) score += 60;
  else score += 20;
  if (!isAsr) score += 50;
  return score;
}

function pickCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  if (!tracks.length) return null;
  return [...tracks].sort((a, b) => trackScore(b) - trackScore(a))[0] ?? null;
}

function xmlCaptionToText(xml: string): string {
  const parts: string[] = [];
  const re = /<text[^>]*>([\s\S]*?)<\/text>/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml))) {
    let t = m[1].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
    t = decodeHtmlEntities(t);
    if (t) parts.push(t);
  }
  return parts.join(" ").replace(/\s+/g, " ").trim();
}

function json3CaptionToText(raw: string): string {
  const data = JSON.parse(raw) as {
    events?: Array<{ segs?: Array<{ utf?: string }> }>;
  };
  const parts: string[] = [];
  for (const ev of data.events || []) {
    for (const seg of ev.segs || []) {
      if (seg.utf) parts.push(seg.utf);
    }
  }
  return parts.join("").replace(/\s+/g, " ").trim();
}

function webvttToText(vtt: string): string {
  const lines = vtt.split(/\r?\n/);
  const parts: string[] = [];
  for (const line of lines) {
    const t = line.trim();
    if (!t || t === "WEBVTT" || /^\d+$/.test(t) || t.includes("-->")) continue;
    parts.push(t);
  }
  return parts.join(" ").replace(/\s+/g, " ").trim();
}

function captionPayloadToText(body: string, contentType: string): string | null {
  const trimmed = body.trim();
  if (!trimmed) return null;

  if (
    contentType.includes("json") ||
    trimmed.startsWith("{") ||
    trimmed.startsWith("[")
  ) {
    try {
      const t = json3CaptionToText(trimmed);
      if (t.length > 0) return t;
    } catch {
      /* fall through */
    }
  }

  if (trimmed.includes("<text")) {
    const t = xmlCaptionToText(trimmed);
    if (t.length > 0) return t;
  }

  if (trimmed.startsWith("WEBVTT") || trimmed.includes("-->")) {
    const t = webvttToText(trimmed);
    if (t.length > 0) return t;
  }

  return null;
}

async function fetchCaptionText(baseUrl: string): Promise<string | null> {
  const urls = [
    baseUrl,
    baseUrl.includes("fmt=") ? baseUrl : `${baseUrl}&fmt=json3`,
    baseUrl.includes("fmt=")
      ? baseUrl.replace(/fmt=[^&]+/, "fmt=vtt")
      : `${baseUrl}&fmt=vtt`,
  ];

  for (const url of urls) {
    const controller = new AbortController();
    const id = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(url, {
        signal: controller.signal,
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          Accept: "*/*",
          "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
        },
      });
      if (!res.ok) continue;
      const body = await res.text();
      const text = captionPayloadToText(
        body,
        res.headers.get("content-type") || ""
      );
      if (text && text.length >= 40) return text.slice(0, MAX_TRANSCRIPT_CHARS);
    } catch {
      /* try next */
    } finally {
      clearTimeout(id);
    }
  }
  return null;
}

export async function fetchYouTubeWatchHtml(
  videoId: string
): Promise<string | null> {
  const watchUrl = `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`;
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(watchUrl, {
      signal: controller.signal,
      redirect: "follow",
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        Accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
      },
    });
    if (!res.ok) return null;
    return await res.text();
  } catch {
    return null;
  } finally {
    clearTimeout(id);
  }
}

export async function extractTranscriptFromWatchHtml(
  html: string,
  videoId: string
): Promise<YouTubeTranscriptResult> {
  const player =
    extractJsonObjectAfterMarker(html, "ytInitialPlayerResponse = ") ||
    extractJsonObjectAfterMarker(html, "var ytInitialPlayerResponse = ") ||
    extractJsonObjectAfterMarker(html, '"ytInitialPlayerResponse":');

  if (!player) {
    return {
      ok: false,
      reason: "영상 자막을 찾지 못했습니다. (플레이어 정보를 읽지 못함)",
    };
  }

  const tracks = getCaptionTracks(player);
  const track = pickCaptionTrack(tracks);
  if (!track?.baseUrl) {
    return {
      ok: false,
      reason:
        "영상 자막을 찾지 못했습니다. 이 영상에 공개된 자막·자동 생성 자막이 없을 수 있습니다.",
    };
  }

  const text = await fetchCaptionText(track.baseUrl);
  if (!text || text.length < 40) {
    return {
      ok: false,
      reason:
        "영상 자막을 찾지 못했습니다. 자막 트랙은 있으나 내용을 가져오지 못했습니다.",
    };
  }

  return {
    ok: true,
    text,
    languageCode: track.languageCode || "unknown",
    isAutoGenerated: track.kind === "asr",
  };
}

export async function fetchYouTubeTranscript(
  pageUrl: string,
  watchHtml?: string | null
): Promise<YouTubeTranscriptResult> {
  const videoId = parseYouTubeVideoId(pageUrl);
  if (!videoId) {
    return { ok: false, reason: "YouTube 영상 ID를 URL에서 찾지 못했습니다." };
  }

  const html = watchHtml ?? (await fetchYouTubeWatchHtml(videoId));
  if (!html) {
    return {
      ok: false,
      reason:
        "영상 자막을 찾지 못했습니다. YouTube 페이지를 불러오지 못했습니다.",
    };
  }

  return extractTranscriptFromWatchHtml(html, videoId);
}
