import type { TranscriptDiagnostic } from "@/lib/from-link/transcriptDiagnostic";
import { MIN_YOUTUBE_TRANSCRIPT_LENGTH } from "@/lib/from-link/transcriptDiagnostic";

type TranscriptDiagnosticPanelProps = {
  transcript: TranscriptDiagnostic;
};

export default function TranscriptDiagnosticPanel({
  transcript,
}: TranscriptDiagnosticPanelProps) {
  if (!transcript.applicable) {
    return (
      <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
        <h2 className="text-lg font-semibold">3. Transcript (자막) 진단</h2>
        <p className="mt-2 text-sm text-gray-600">
          YouTube 링크가 아니므로 자막 추출 진단은 해당하지 않습니다.
        </p>
      </section>
    );
  }

  const statusLabel = transcript.success ? "성공" : "실패";
  const statusClass = transcript.success
    ? "border-emerald-200 bg-emerald-50 text-emerald-900"
    : "border-red-200 bg-red-50 text-red-900";

  const lengthOk =
    transcript.success && transcript.length >= MIN_YOUTUBE_TRANSCRIPT_LENGTH;

  return (
    <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
      <h2 className="text-lg font-semibold">3. Transcript (자막) 진단</h2>
      <p className="mt-2 text-sm text-gray-600">
        후보 생성 전에 자막 추출 결과를 확인합니다. 자막이 없거나 너무 짧으면 제목·설명만으로 후보를
        만들지 않습니다.
      </p>

      <dl className="mt-4 grid gap-3 text-sm md:grid-cols-2">
        <div className={`rounded-xl border p-4 ${statusClass}`}>
          <dt className="text-xs font-semibold uppercase tracking-wide opacity-80">
            추출 성공 여부
          </dt>
          <dd className="mt-1 text-lg font-semibold">{statusLabel}</dd>
        </div>
        <div className="rounded-xl border border-gray-100 bg-gray-50 p-4">
          <dt className="text-xs font-semibold uppercase tracking-wide text-gray-500">
            Transcript 길이
          </dt>
          <dd className="mt-1 font-medium text-gray-900">
            {transcript.length.toLocaleString("ko-KR")}자
            {transcript.success ? (
              <span className="mt-1 block text-xs font-normal text-gray-600">
                후보 생성 최소: {MIN_YOUTUBE_TRANSCRIPT_LENGTH.toLocaleString("ko-KR")}자
                {lengthOk ? " · 충족" : " · 미달"}
              </span>
            ) : null}
          </dd>
        </div>
        {transcript.language ? (
          <div className="rounded-xl border border-gray-100 bg-gray-50 p-4">
            <dt className="text-xs font-semibold uppercase tracking-wide text-gray-500">
              자막 언어
            </dt>
            <dd className="mt-1 text-gray-900">
              {transcript.language}
              {transcript.isAutoGenerated ? " (자동 생성)" : " (제공 자막)"}
            </dd>
          </div>
        ) : null}
        {transcript.failureReason && !transcript.success ? (
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 md:col-span-2 text-amber-900">
            <dt className="text-xs font-semibold uppercase tracking-wide">실패 사유</dt>
            <dd className="mt-1">{transcript.failureReason}</dd>
          </div>
        ) : null}
      </dl>

      {transcript.success && transcript.preview500 ? (
        <div className="mt-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
            Transcript 앞부분 500자 미리보기
          </p>
          <div className="mt-2 max-h-48 overflow-y-auto rounded-xl border border-gray-100 bg-gray-50 p-4">
            <p className="whitespace-pre-wrap text-sm leading-relaxed text-gray-900">
              {transcript.preview500}
              {transcript.length > 500 ? (
                <span className="text-gray-500"> …</span>
              ) : null}
            </p>
          </div>
        </div>
      ) : null}

      {!transcript.success ? (
        <p className="mt-4 text-sm text-red-800">
          영상 자막을 찾지 못했습니다. 제목·설명문만으로는 후보를 생성하지 않습니다.
        </p>
      ) : null}
      {transcript.success && !lengthOk ? (
        <p className="mt-4 text-sm text-red-800">
          영상 자막이 너무 짧아 후보를 생성하지 않습니다. 더 긴 자막이 있는 영상을 사용해
          주세요.
        </p>
      ) : null}
    </section>
  );
}
