/**
 * Built-in collection fields for admin checkbox UI.
 * Keywords are defaults; admins may override collect/exclude lists in profile.
 * AI importance scoring is unchanged — this only gates pre-AI intake.
 */

export type CollectionFieldRealm =
  | "politics"
  | "economy"
  | "society"
  | "public_health"
  | "culture"
  | "science"
  | "lifestyle";

export type BuiltInCollectionField = {
  id: string;
  realm: CollectionFieldRealm;
  labelKo: string;
  /** Default ON for hard-news; OFF for soft lifestyle noise. */
  defaultEnabled: boolean;
  collectKeywords: string[];
  excludeKeywords: string[];
};

export const COLLECTION_REALM_LABELS: Record<CollectionFieldRealm, string> = {
  politics: "정치",
  economy: "경제",
  society: "사회",
  public_health: "공중보건",
  culture: "문화",
  science: "과학",
  lifestyle: "생활·기타",
};

export const COLLECTION_REALM_ORDER: CollectionFieldRealm[] = [
  "politics",
  "economy",
  "society",
  "public_health",
  "culture",
  "science",
  "lifestyle",
];

/** Region scope shown on the simple admin screen. */
export type CollectionRegionScope = "all" | "korea" | "us" | "intl";

export const COLLECTION_REGION_SCOPE_LABELS: Record<
  CollectionRegionScope,
  string
> = {
  all: "전체",
  korea: "한국",
  us: "미국",
  intl: "국제",
};

export const BUILT_IN_COLLECTION_FIELDS: BuiltInCollectionField[] = [
  // 정치
  {
    id: "politics.government",
    realm: "politics",
    labelKo: "정부·입법",
    defaultEnabled: true,
    collectKeywords: [
      "정부",
      "입법",
      "국회",
      "의회",
      "대통령",
      "총리",
      "행정부",
      "congress",
      "parliament",
      "legislation",
      "white house",
      "cabinet",
    ],
    excludeKeywords: [],
  },
  {
    id: "politics.elections",
    realm: "politics",
    labelKo: "선거",
    defaultEnabled: true,
    collectKeywords: [
      "선거",
      "투표",
      "대선",
      "총선",
      "경선",
      "election",
      "primary",
      "ballot",
      "voter",
      "campaign",
    ],
    excludeKeywords: [],
  },
  {
    id: "politics.diplomacy",
    realm: "politics",
    labelKo: "외교",
    defaultEnabled: true,
    collectKeywords: [
      "외교",
      "정상회담",
      "대사",
      "조약",
      "diplomacy",
      "diplomatic",
      "summit",
      "ambassador",
      "treaty",
      "foreign ministry",
    ],
    excludeKeywords: [],
  },
  {
    id: "politics.defense",
    realm: "politics",
    labelKo: "국방·안보·전쟁·북한",
    defaultEnabled: true,
    collectKeywords: [
      "국방",
      "안보",
      "전쟁",
      "북한",
      "미사일",
      "핵",
      "군사",
      "defense",
      "national security",
      "war",
      "north korea",
      "missile",
      "nuclear",
      "invasion",
    ],
    excludeKeywords: [],
  },
  {
    id: "politics.courts",
    realm: "politics",
    labelKo: "법원·제도",
    defaultEnabled: true,
    collectKeywords: [
      "법원",
      "대법원",
      "재판",
      "헌법",
      "검찰",
      "court",
      "supreme court",
      "judicial",
      "prosecutor",
      "constitution",
    ],
    excludeKeywords: [],
  },
  {
    id: "politics.rights",
    realm: "politics",
    labelKo: "인권·종교 자유",
    defaultEnabled: true,
    collectKeywords: [
      "인권",
      "종교 자유",
      "종교자유",
      "소수자",
      "human rights",
      "religious freedom",
      "civil liberties",
      "persecution",
    ],
    excludeKeywords: [],
  },
  // 경제
  {
    id: "economy.rates",
    realm: "economy",
    labelKo: "금리·물가",
    defaultEnabled: true,
    collectKeywords: [
      "금리",
      "물가",
      "인플레이션",
      "중앙은행",
      "연준",
      "interest rate",
      "inflation",
      "federal reserve",
      "central bank",
      "cpi",
    ],
    excludeKeywords: [],
  },
  {
    id: "economy.markets",
    realm: "economy",
    labelKo: "금융시장",
    defaultEnabled: true,
    collectKeywords: [
      "주식",
      "증시",
      "금융시장",
      "환율",
      "채권",
      "stock market",
      "wall street",
      "equities",
      "bond",
      "forex",
    ],
    excludeKeywords: [],
  },
  {
    id: "economy.trade",
    realm: "economy",
    labelKo: "무역·관세",
    defaultEnabled: true,
    collectKeywords: [
      "무역",
      "관세",
      "수출",
      "수입",
      "통상",
      "tariff",
      "trade war",
      "export",
      "import",
      "sanctions",
    ],
    excludeKeywords: [],
  },
  {
    id: "economy.business",
    realm: "economy",
    labelKo: "기업·산업",
    defaultEnabled: true,
    collectKeywords: [
      "기업",
      "산업",
      "실적",
      "인수합병",
      "반도체",
      "corporation",
      "earnings",
      "merger",
      "industry",
      "ceo",
    ],
    excludeKeywords: [],
  },
  {
    id: "economy.energy",
    realm: "economy",
    labelKo: "에너지",
    defaultEnabled: true,
    collectKeywords: [
      "에너지",
      "석유",
      "가스",
      "원유",
      "전력",
      "oil",
      "crude",
      "natural gas",
      "energy",
      "opec",
    ],
    excludeKeywords: [],
  },
  {
    id: "economy.housing",
    realm: "economy",
    labelKo: "주택·고용",
    defaultEnabled: true,
    collectKeywords: [
      "주택",
      "부동산",
      "고용",
      "실업",
      "일자리",
      "housing",
      "mortgage",
      "unemployment",
      "jobs report",
      "labor market",
    ],
    excludeKeywords: [],
  },
  // 사회
  {
    id: "society.disaster",
    realm: "society",
    labelKo: "재난·대형 사고",
    defaultEnabled: true,
    collectKeywords: [
      "재난",
      "대형 사고",
      "지진",
      "홍수",
      "산불",
      "폭발",
      "disaster",
      "earthquake",
      "flood",
      "wildfire",
      "explosion",
      "mass casualty",
    ],
    excludeKeywords: [],
  },
  {
    id: "society.crime",
    realm: "society",
    labelKo: "범죄·공공안전",
    defaultEnabled: true,
    collectKeywords: [
      "범죄",
      "경찰",
      "공공안전",
      "총격",
      "테러",
      "crime",
      "police",
      "shooting",
      "terrorism",
      "public safety",
    ],
    excludeKeywords: [],
  },
  {
    /**
     * Legacy id kept so existing field_settings rows are not dropped.
     * New installs default OFF; use public_health.infectious instead.
     */
    id: "society.health",
    realm: "society",
    labelKo: "감염병·공중보건(이전)",
    defaultEnabled: false,
    collectKeywords: [
      "감염병",
      "공중보건",
      "코로나",
      "확진",
      "팬데믹",
      "epidemic",
      "pandemic",
      "outbreak",
      "public health",
      "cdc",
      "who",
    ],
    excludeKeywords: [
      "컴퓨터 바이러스",
      "computer virus",
      "malware",
      "다이어트",
      "diet tip",
      "연예인 건강",
      "celebrity health",
      "health tips",
    ],
  },
  // 공중보건 (독립 분야)
  {
    id: "public_health.infectious",
    realm: "public_health",
    labelKo: "공중보건·감염병",
    defaultEnabled: true,
    collectKeywords: [
      "공중보건",
      "감염병",
      "전염병",
      "확진",
      "집단감염",
      "팬데믹",
      "유행",
      "발병",
      "확산",
      "보건당국",
      "질병관리청",
      "세계보건기구",
      "public health",
      "infectious disease",
      "outbreak",
      "epidemic",
      "pandemic",
      "hospitalization",
      "cdc",
      "who",
      "measles",
      "mpox",
      "ebola",
      "cholera",
      "covid-19",
      "avian flu",
    ],
    excludeKeywords: [
      "컴퓨터 바이러스",
      "computer virus",
      "malware",
      "ransomware",
      "다이어트",
      "diet tip",
      "weight loss",
      "연예인 건강",
      "celebrity health",
      "health tips",
      "wellness hack",
      "생활 건강",
    ],
  },
  {
    id: "society.migration",
    realm: "society",
    labelKo: "이민·난민",
    defaultEnabled: true,
    collectKeywords: [
      "이민",
      "난민",
      "망명",
      "국경",
      "immigration",
      "refugee",
      "asylum",
      "migrant",
      "border",
    ],
    excludeKeywords: [],
  },
  {
    id: "society.education",
    realm: "society",
    labelKo: "교육·노동",
    defaultEnabled: true,
    collectKeywords: [
      "교육",
      "학교",
      "노동",
      "파업",
      "노조",
      "education",
      "school",
      "labor",
      "strike",
      "union",
    ],
    excludeKeywords: [],
  },
  // 문화
  {
    id: "culture.religion",
    realm: "culture",
    labelKo: "종교",
    defaultEnabled: true,
    collectKeywords: [
      "종교",
      "교회",
      "사찰",
      "이슬람",
      "기독교",
      "religion",
      "church",
      "mosque",
      "temple",
      "faith",
    ],
    excludeKeywords: [],
  },
  {
    id: "culture.arts",
    realm: "culture",
    labelKo: "예술·문화재",
    defaultEnabled: false,
    collectKeywords: [
      "예술",
      "문화재",
      "박물관",
      "전시",
      "arts",
      "museum",
      "heritage",
      "exhibition",
      "cultural property",
    ],
    excludeKeywords: [],
  },
  {
    id: "culture.media",
    realm: "culture",
    labelKo: "미디어",
    defaultEnabled: true,
    collectKeywords: [
      "언론",
      "미디어",
      "방송",
      "가짜뉴스",
      "media",
      "press freedom",
      "journalism",
      "broadcast",
      "disinformation",
    ],
    excludeKeywords: [],
  },
  {
    id: "culture.entertainment",
    realm: "culture",
    labelKo: "연예",
    defaultEnabled: false,
    collectKeywords: [
      "연예",
      "아이돌",
      "드라마",
      "영화 배우",
      "celebrity",
      "entertainment",
      "hollywood",
      "k-pop",
      "hollywood gossip",
    ],
    excludeKeywords: [
      "연예 가십",
      "셀럽 스캔들",
      "celebrity gossip",
      "red carpet",
    ],
  },
  // 과학
  {
    id: "science.medical",
    realm: "science",
    labelKo: "의료 연구",
    defaultEnabled: true,
    collectKeywords: [
      "의료 연구",
      "임상",
      "신약",
      "의학",
      "clinical trial",
      "medical research",
      "vaccine research",
      "biotech",
    ],
    excludeKeywords: [],
  },
  {
    id: "science.space",
    realm: "science",
    labelKo: "우주",
    defaultEnabled: true,
    collectKeywords: [
      "우주",
      "로켓",
      "위성",
      "nasa",
      "space",
      "rocket",
      "satellite",
      "astronaut",
      "spacex",
    ],
    excludeKeywords: [],
  },
  {
    id: "science.climate",
    realm: "science",
    labelKo: "기후·환경",
    defaultEnabled: true,
    collectKeywords: [
      "기후",
      "환경",
      "탄소",
      "온난화",
      "climate",
      "global warming",
      "emissions",
      "environment",
      "biodiversity",
    ],
    excludeKeywords: [],
  },
  {
    id: "science.tech",
    realm: "science",
    labelKo: "기술",
    defaultEnabled: true,
    collectKeywords: [
      "인공지능",
      "AI",
      "반도체 기술",
      "사이버",
      "artificial intelligence",
      "cybersecurity",
      "chip technology",
      "software",
    ],
    excludeKeywords: [],
  },
  {
    id: "science.curiosity",
    realm: "science",
    labelKo: "흥미성 과학",
    defaultEnabled: false,
    collectKeywords: [
      "흥미 과학",
      "신기한 발견",
      "curious science",
      "weird science",
      "fun fact",
      "amazing discovery",
    ],
    excludeKeywords: [
      "고양이 연구",
      "귀여운 동물",
      "cute animal study",
      "viral science",
    ],
  },
  // 생활·기타
  {
    id: "lifestyle.travel",
    realm: "lifestyle",
    labelKo: "여행·음식·패션",
    defaultEnabled: false,
    collectKeywords: [
      "여행",
      "맛집",
      "패션",
      "레시피",
      "travel tip",
      "restaurant review",
      "fashion week",
      "recipe",
    ],
    excludeKeywords: [
      "여행 팁",
      "맛집 추천",
      "패션 화보",
      "travel tips",
      "best restaurants",
    ],
  },
  {
    id: "lifestyle.astrology",
    realm: "lifestyle",
    labelKo: "운세·점성술",
    defaultEnabled: false,
    collectKeywords: [
      "운세",
      "점성술",
      "별자리",
      "horoscope",
      "astrology",
      "zodiac",
    ],
    excludeKeywords: ["오늘의 운세", "daily horoscope", "zodiac sign"],
  },
  {
    id: "lifestyle.quotes",
    realm: "lifestyle",
    labelKo: "좋은 글·명언",
    defaultEnabled: false,
    collectKeywords: [
      "명언",
      "좋은 글",
      "감동 사연",
      "inspirational quote",
      "feel-good story",
      "heartwarming",
    ],
    excludeKeywords: ["명언 모음", "inspirational quotes"],
  },
  {
    id: "lifestyle.local",
    realm: "lifestyle",
    labelKo: "지역 행사·홍보",
    defaultEnabled: false,
    collectKeywords: [
      "지역 행사",
      "축제 홍보",
      "할인 행사",
      "local event",
      "festival promo",
      "community fair",
      "sponsored event",
    ],
    excludeKeywords: ["홍보성", "광고성", "sponsored content"],
  },
  {
    id: "lifestyle.sports",
    realm: "lifestyle",
    labelKo: "일상 스포츠",
    defaultEnabled: false,
    collectKeywords: [
      "경기 결과",
      "리그 순위",
      "스포츠 하이라이트",
      "game recap",
      "box score",
      "league standings",
      "match highlights",
    ],
    excludeKeywords: ["경기 결과만", "routine sports result"],
  },
];

export function getBuiltInFieldById(
  id: string
): BuiltInCollectionField | undefined {
  return BUILT_IN_COLLECTION_FIELDS.find((f) => f.id === id);
}
