import type { HomeNewsLabels } from "@/components/home/HomeNewsView";

export const enHomeLabels: HomeNewsLabels = {
  edition: "Hannoon",
  tagline:
    "Global news at a glance. Editor-reviewed stories in English — headlines, categories, and major outlets.",
  navLatest: "Latest",
  navCategories: "Categories",
  navSources: "Sources",
  alternateLang: "한국어",
  featuredEyebrow: "Headline",
  featuredTitle: "Top story",
  readArticle: "Read article",
  latestEyebrow: "Latest",
  latestTitle: "More of Today's Top Stories",
  latestDesc: "More stories published today from Korea and the US.",
  columnEmpty: "No stories in this column.",
  trendingTitle: "Trending Issues",
  trendingRegionUs: "United States",
  trendingRegionKr: "Korea",
  trendingRelatedLabel: "Related stories",
  trendingOriginalLabel: "Original source",
  categoriesEyebrow: "Categories",
  categoriesTitle: "Stories by category",
  categoriesEmpty: "No published stories in this category.",
  sourcesEyebrow: "Sources",
  sourcesTitle: "Major outlets",
  sourcesDesc:
    "Source outlets currently represented among published stories.",
  sourceLeadsTitle: "Lead stories by source",
  sidebarEyebrow: "More",
  sidebarTitle: "More headlines",
  sidebarDesc: "Latest published stories by date.",
  navHome: "Hannoon home",
  empty: "There are no published English articles yet.",
  errorPrefix: "Error loading data:",
  noImage: "No image",
  previousHighlightsTitle: "Previous Top Stories",
  previousHighlightsDesc:
    "Important stories from yesterday and the past 7 days.",
  editionHeaderTodayLabel: "Today's Hannoon",
  continuingIssueLabel: "Ongoing issue",
};
